
language: java

jdk:
    - openjdk6
    - openjdk7
    - oraclejdk6
    - oraclejdk7

branches:
  only:
    - master

before_script:
     - chmod +x grailsw
     - chmod +x test/apps/gson-test/grailsw
     - chmod +x test/apps/jsonapi-test/grailsw

script: ./grailsw refresh-dependencies
        && ./grailsw "test-app -unit"
        && cd test/apps/gson-test
        && ./grailsw refresh-dependencies
        && ./grailsw "test-app -functional"
        && cd ../jsonapi-test
        && ./grailsw refresh-dependencies
        && ./grailsw "test-app -functional"
